### PR TITLE
Modify phoneticize.py's output to match requirements

### PR DESCRIPTION
**Pull request by julienbaley**

### CODE REVIEW

**Comment by julienbaley** [comment]
Sorry, opened the PR in the wrong place for now :)

**Comment by AdolfVonKleist** [comment]
OK, just FYI that script is only intended to kind of provide a simple example of what kind of what the binding provide access to, so you can build something that solves a real problem.

**Comment by julienbaley** [comment]
Ah, that's a good point (I hacked phoneticize.py in a rush some months ago).
Do the bindings support python 3?

**Comment by AdolfVonKleist** [comment]
They probably do not support python 3, but I have never tried to compile with them.  That would be a welcome addition, but it would need to apply to all the python scripts, and I have no idea how much work would be involved.

**Comment by julienbaley** [comment]
Are you, in principle, welcoming contributions in that area?
And would you aim for support of both (harder) or is python 3 sufficient (cleaner)?
Python 2.7, the last 2.x version, is actually going to be unsupported in 2020.

**Comment by AdolfVonKleist** [comment]
Yes, but we would need to keep support for python2.x.  I agree it would be cleaner to move to 3, but it would break compatibility in other places, so it would need to be a more gradual transition.

**Comment by julienbaley** [comment]
Hmm, that may be too much to maintain for me.
However, I can see that compatibility was broken in the methods themselves, since model.Phoneticize now takes only 5 arguments instead of 7 (and phoneticize.py wasn't update to reflect this).
I'm not too familiar with how bindings work, the only thing I can find here is that https://github.com/AdolfVonKleist/Phonetisaurus/blob/master/phonetisaurus/__init__.py  ; where does this "Phonetisaurus" point to?

**Pull request closed without merging**
